# Generated by Django 5.1.1 on 2024-10-02 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("configure_flags", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PythonVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_hash", models.CharField(max_length=40, unique=True)),
                ("commit_date", models.DateTimeField()),
                ("version_string", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SizeMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_date", models.DateTimeField(auto_now_add=True)),
                ("size_data", models.TextField()),
                ("total_size", models.BigIntegerField()),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.configuration",
                    ),
                ),
                (
                    "python_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.pythonversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("python_version", "configuration")},
            },
        ),
        migrations.CreateModel(
            name="BloatyOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("output", models.TextField()),
                (
                    "size_measurement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.sizemeasurement",
                    ),
                ),
            ],
        ),
    ]
